### ISSUE TITLE
The setup menu only lists the first page of the `/user/repos` rest API

### ISSUE THREAD

**Issue by p0lygun** [The0zzy/bf2042-portal-github-plugin#1]
![Screenshot 2022-09-14 02:18:50](https://user-images.githubusercontent.com/22869882/190007431-fe04fb32-b6eb-4e97-b268-55dc9ea7efe0.png)

### Possible solution 
When the user scrolls to the bottom of current choices load the next page in the rest API

**Comment by The0zzy** [comment]
For collaboration repos, there is still no solution - add pagination headers and traverse through all results.
